# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U11I_MkQP32uuvatKhuiZi9Hn358Dl_B

Build a 2-layer neural network step by step

1- Initiliaze the parameters
"""

import numpy as np

def initiliaze_parameters(x , h , y):

np.random.seed(1)

w1 = np.random.randn( h , x) * 0.01
b1 = np.zeros((h , 1))
w2 = np.random.randn( y , h) * 0.01
b2 = np.zeros((y , 1))

parameters ={
    'w1' = w1,
    'b1' = b1,
    'w2' = w2,
    'b2' = b2
}

return parameters

parameters = initiliaze_parameters(3 , 2 , 1)
print(parameters['w1'])
print(parameters['b1'])
print(parameters['w2'])
print(parameters['b2'])